import 'package:cipher_saver/layouts/enter_layout.dart';
import 'package:cipher_saver/layouts/main_layout.dart';
import 'package:cipher_saver/screens/enter.dart';
import 'package:cipher_saver/screens/enter_cipher.dart';
import 'package:cipher_saver/screens/menu.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(const App());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Khand',
        primaryColor: const Color(0xFFFFD600)
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const EnterLayout(pageContent: EnterIndex(),),
        '/enter-cipher': (context) => EnterLayout(pageContent: EnterCipher(),),
        '/menu': (context) => MainLayout(pageContent: Menu())
      },
    );
  }
}
